version: '3.8'

services:
  api_gateway:
    build:
      context: ./api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - student_service
      - booking_service
      - course_service
      - trainer_service
      - schedule_service
    networks:
      - training-network

  student_service:
    build:
      context: ./microservices/student_service
    ports:
      - "8002:8000"
    networks:
      - training-network

  booking_service:
    build:
      context: ./microservices/booking_service
    ports:
      - "8003:8000"
    networks:
      - training-network

  course_service:
    build:
      context: ./microservices/course_service
    ports:
      - "8004:8000"
    networks:
      - training-network

  trainer_service:
    build:
      context: ./microservices/trainer_service
    ports:
      - "8005:8000"
    networks:
      - training-network

  schedule_service:
    build:
      context: ./microservices/schedule_service
    ports:
      - "8006:8000"
    networks:
      - training-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "8007:8000"
    networks:
      - training-network

networks:
  training-network:
    driver: bridge

